USE [RC3_Data]
GO

/****** Object:  StoredProcedure [dbo].[APP_UPDATE_TRUE_UP]    Script Date: 9/30/2019 4:30:41 PM ******/
DROP PROCEDURE [dbo].[APP_UPDATE_TRUE_UP]
GO

/****** Object:  StoredProcedure [dbo].[APP_UPDATE_TRUE_UP]    Script Date: 9/30/2019 4:30:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<MOLLY MARGOLIS>
-- Create date: <7/27/2018>
-- Description:	<Description,,>

-- Modified By: <Kalyan Kalagotla>
-- Modified Date : <09/23/2019>
-- Description : <Added new model codes for K-Latte, K-Duo Brewer>
-- Requested By : <Lina Tran>
-- =============================================
CREATE PROCEDURE  [dbo].[APP_UPDATE_TRUE_UP]

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @t1 DATETIME;
DECLARE @t2 DATETIME;

/*Record start time. */
SET @t1 = GETDATE();

TRUNCATE TABLE RC3_Data..APP_TRUE_UP	

/************ K-LATTE *************************/
-- K-LATTE RETURNS TO CALL CENTER -----
IF OBJECT_ID ('tempdb..#KLATTE') IS NOT NULL 
DROP TABLE #KLATTE

SELECT DISTINCT D.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, D.SALE_RETAILER_NAME AS RETAILER, 
       'CALL CENTER RETURN' AS TRANSACTION_TYPE, CAST(E.OPENED_DT AS DATE) AS TRANSACTION_DATE, A.MANU_SITE
INTO #KLATTE
FROM EPMMarts..DIM_CRM_BREWER A          
       INNER JOIN EPMMarts..FACT_CRM_BREWER B ON A.BREWER_SGK=B.BREWER_SGK  
       INNER JOIN KQUP_PROD..SIRAS_POS D ON A.SERIAL_NUMBER=D.SERIAL_NUMBER 
       INNER JOIN RC3_Data.[dbo].[APP_SERVICE_REQ] E ON D.SERIAL_NUMBER=E.SERIAL_NUM     
WHERE A.MODEL_CODE IN ('36', '82', '83', '84', '90', '5000', '5100', '5200') AND WARRANTY_IND ='Y' AND D.SALE_QUANTITY=1 AND RESALE_QUANTITY='0'


----K-LATTE RETURNS TO RETAIL----
INSERT INTO #KLATTE
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
       'RETAIL RETURN' AS TRANSACTION_TYPE, CAST(RETURN_TRANSACTION_DATE AS DATE)  AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A          
       INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER       
WHERE MODEL_CODE IN ('36', '82', '83', '84', '90', '5000', '5100', '5200') AND SALE_QUANTITY='1' AND C.RETURN_QUANTITY=1 AND RESALE_QUANTITY='0'

----FIND EARLIEST K-LATTE RETURN DATE----
IF OBJECT_ID ('tempdb..#K_LATTE_MIN_RETURN_DATE') IS NOT NULL 
DROP TABLE #K_LATTE_MIN_RETURN_DATE 

SELECT DISTINCT SERIAL_NUMBER, MIN(TRANSACTION_DATE) AS TRANSACTION_DATE
INTO #K_LATTE_MIN_RETURN_DATE
FROM #KLATTE
GROUP BY  SERIAL_NUMBER

----REMOVE LATER K-LATTE RETURN DATE FROM TABLE----
INSERT INTO RC3_Data..APP_TRUE_UP
SELECT A.* , getdate() dt
FROM #KLATTE A
INNER JOIN #K_LATTE_MIN_RETURN_DATE B ON A.SERIAL_NUMBER=B.SERIAL_NUMBER AND A.TRANSACTION_DATE=B.TRANSACTION_DATE

----K-LATTE SIRAS RESALES----
INSERT INTO #KLATTE
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
       'RESALE' AS TRANSACTION_TYPE, CAST(RESALE_TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A          
       INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER       
WHERE MODEL_CODE IN ('36', '82', '83', '84', '90', '5000', '5100', '5200') AND SALE_QUANTITY='1' AND C.RESALE_QUANTITY=1

----K-LATTE SIRAS SALES----
INSERT INTO #KLATTE
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
       'SALE' AS TRANSACTION_TYPE, CAST(SALE_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A          
       INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER       
WHERE MODEL_CODE IN ('36', '82', '83', '84', '90', '5000', '5100', '5200') AND C.SALE_QUANTITY=1 AND RESALE_QUANTITY='0'

----ADD LATTE SALES AND RESALES TO TABLE----
INSERT INTO RC3_Data..APP_TRUE_UP	
SELECT DISTINCT *, getdate() dt
FROM #KLATTE
WHERE TRANSACTION_TYPE<>'RETURN'


/****** K-35 Brewer *********/
----K35 RETURNS TO CALL CENTER----
SELECT DISTINCT D.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, D.SALE_RETAILER_NAME AS RETAILER, 
	'CALL CENTER RETURN' AS TRANSACTION_TYPE, CAST(E.OPENED_DT AS DATE) AS TRANSACTION_DATE, A.MANU_SITE
INTO #SIRAS
FROM EPMMarts..DIM_CRM_BREWER A 		
	INNER JOIN EPMMarts..FACT_CRM_BREWER B ON A.BREWER_SGK=B.BREWER_SGK	
	INNER JOIN KQUP_PROD..SIRAS_POS D ON A.SERIAL_NUMBER=D.SERIAL_NUMBER	
	INNER JOIN RC3_Data.[dbo].[APP_SERVICE_REQ] E ON D.SERIAL_NUMBER=E.SERIAL_NUM 	
WHERE A.MODEL_CODE='35' AND WARRANTY_IND ='Y' AND D.SALE_QUANTITY=1 AND RESALE_QUANTITY='0'

----K35 RETURNS TO RETAIL----
INSERT INTO #SIRAS
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
	'RETAIL RETURN' AS TRANSACTION_TYPE, CAST(RETURN_TRANSACTION_DATE AS DATE)  AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER 	
WHERE MODEL_CODE='35' AND SALE_QUANTITY='1' AND C.RETURN_QUANTITY=1 AND RESALE_QUANTITY='0'

----FIND EARLIEST K35 RETURN DATE----
SELECT DISTINCT SERIAL_NUMBER, MIN(TRANSACTION_DATE) AS TRANSACTION_DATE
INTO #MIN_RETURN_DATE
FROM #SIRAS
GROUP BY  SERIAL_NUMBER

----REMOVE LATER K35 RETURN DATE FROM TABLE----
INSERT INTO RC3_Data..APP_TRUE_UP
SELECT A.* , getdate()
FROM #SIRAS A
INNER JOIN #MIN_RETURN_DATE B ON A.SERIAL_NUMBER=B.SERIAL_NUMBER AND A.TRANSACTION_DATE=B.TRANSACTION_DATE
--select * from #SIRAS

----35 SIRAS RESALES----
INSERT INTO #SIRAS
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
	'RESALE' AS TRANSACTION_TYPE, CAST(RESALE_TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER 	
WHERE MODEL_CODE='35' AND SALE_QUANTITY='1' AND C.RESALE_QUANTITY=1

----K35 SIRAS SALES----
INSERT INTO #SIRAS
SELECT DISTINCT A.SERIAL_NUMBER, A.MODEL_CODE, A.MODEL_FAMILY, SALE_RETAILER_NAME AS RETAILER, 
	'SALE' AS TRANSACTION_TYPE, CAST(SALE_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER 	
WHERE MODEL_CODE='35' AND C.SALE_QUANTITY=1 AND RESALE_QUANTITY='0'

----ADD K35 SALES AND RESALES TO TABLE----
INSERT INTO RC3_Data..APP_TRUE_UP	
SELECT DISTINCT *, getdate()
FROM #SIRAS
WHERE TRANSACTION_TYPE<>'RETURN'

--------------- K-MINI ---------------------------------------------------
----KMINI CALL CENTER RETURNS----
SELECT DISTINCT D.SERIAL_NUMBER,
	CASE WHEN D.SERIAL_NUMBER LIKE '21P.%' THEN '21P'
		WHEN D.SERIAL_NUMBER LIKE '21B.%' THEN '21B'
		END AS MODEL_CODE,

	CASE WHEN D.SERIAL_NUMBER LIKE '21P.%' THEN 'K-MINI PLUS'
		WHEN D.SERIAL_NUMBER LIKE '21B.%' THEN 'K-MINI BASIC'
		END AS MODEL_FAMILY,

	D.SALE_RETAILER_NAME AS RETAILER, 'CALL CENTER RETURN' AS TRANSACTION_TYPE,
	CAST(OPENED_DT AS DATE) AS TRANSACTION_DATE, A.MANU_SITE
INTO #MINI
FROM EPMMarts..DIM_CRM_BREWER A 		
	INNER JOIN EPMMarts..FACT_CRM_BREWER B ON A.BREWER_SGK=B.BREWER_SGK	
	INNER JOIN KQUP_PROD..SIRAS_POS D ON A.SERIAL_NUMBER=D.SERIAL_NUMBER	
	INNER JOIN RC3_Data.[dbo].[APP_SERVICE_REQ] E ON D.SERIAL_NUMBER=E.SERIAL_NUM 	
WHERE WARRANTY_IND ='Y'	AND D.SALE_QUANTITY=1 AND D.RESALE_QUANTITY=0
	AND (D.SERIAL_NUMBER LIKE '21B%' OR D.SERIAL_NUMBER LIKE '21P%')
	AND UPC IN ('611247373064','611247374313')

----KMINI RETURNS TO RETAIL----
INSERT INTO #MINI
SELECT DISTINCT A.SERIAL_NUMBER,
	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN '21P'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN '21B'
		END AS MODEL_CODE,

	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN 'K-MINI PLUS'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN 'K-MINI BASIC'
		END AS MODEL_FAMILY,

	SALE_RETAILER_NAME AS RETAILER, 'RETAIL RETURN' AS TRANSACTION_TYPE, 
	CAST(RETURN_TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER
WHERE SALE_DATE >= GETDATE() - 365 AND SALE_QUANTITY=1 AND RETURN_QUANTITY=1 AND RESALE_QUANTITY=0
	AND (A.SERIAL_NUMBER LIKE '21B%' OR A.SERIAL_NUMBER LIKE '21P%')
	AND UPC IN ('611247373064','611247374313')

----FIND EARLIEST KMINI RETURN DATE----
SELECT DISTINCT SERIAL_NUMBER, MIN(TRANSACTION_DATE) AS TRANSACTION_DATE
INTO #MIN_RETURN_DATE_MINI
FROM #MINI
GROUP BY  SERIAL_NUMBER

----REMOVE LATER KMINI RETURN DATE FROM TABLE----
INSERT INTO RC3_Data..APP_TRUE_UP
SELECT A.* , getdate()
FROM #MINI A
INNER JOIN #MIN_RETURN_DATE_MINI B ON A.SERIAL_NUMBER=B.SERIAL_NUMBER AND A.TRANSACTION_DATE=B.TRANSACTION_DATE

----KMINI SIRAS RESALES----
INSERT INTO #MINI
SELECT DISTINCT A.SERIAL_NUMBER, 
	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN '21P'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN '21B'
	END AS MODEL_CODE,

	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN 'K-MINI PLUS'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN 'K-MINI BASIC'
	END AS MODEL_FAMILY,

	SALE_RETAILER_NAME AS RETAILER, 'RESALE' AS TRANSACTION_TYPE, 
	CAST(SALE_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER 					
	WHERE SALE_DATE >= GETDATE() - 365
	AND	SALE_QUANTITY=1 AND RESALE_QUANTITY =1 AND (A.SERIAL_NUMBER LIKE '21B%' OR A.SERIAL_NUMBER LIKE '21P%')
	AND UPC IN ('611247373064','611247374313')

----KMINI SIRAS SALES----
INSERT INTO #MINI
SELECT DISTINCT A.SERIAL_NUMBER, 
	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN '21P'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN '21B'
	END AS MODEL_CODE,

	CASE WHEN A.SERIAL_NUMBER LIKE '21P.%' THEN 'K-MINI PLUS'
		WHEN A.SERIAL_NUMBER LIKE '21B.%' THEN 'K-MINI BASIC'
	END AS MODEL_FAMILY,

	SALE_RETAILER_NAME AS RETAILER, 'SALE' AS TRANSACTION_TYPE, 
	CAST(SALE_DATE AS DATE) AS TRANSACTION_DATE, MANU_SITE
FROM EPMMarts..DIM_CRM_BREWER A		
	INNER JOIN KQUP_PROD..SIRAS_POS C ON A.SERIAL_NUMBER=C.SERIAL_NUMBER					
	WHERE SALE_DATE >= GETDATE() - 365
	AND	SALE_QUANTITY=1 AND RESALE_QUANTITY =0 AND (A.SERIAL_NUMBER LIKE '21B%' OR A.SERIAL_NUMBER LIKE '21P%')
	AND UPC IN ('611247373064','611247374313')

INSERT INTO RC3_Data..APP_TRUE_UP
SELECT DISTINCT *, GETDATE()
FROM #MINI
WHERE TRANSACTION_TYPE<>'RETURN'






--NEED TO CHANGE TO ndt
TRUNCATE TABLE RC3_Data..APP_TRUE_UP_NDT
INSERT INTO RC3_Data..APP_TRUE_UP_NDT
SELECT DISTINCT A.MODEL_FAMILY, CAST(A.QTY AS FLOAT)/CAST(B.QTY AS FLOAT) AS RATE
FROM
	(SELECT MODEL_FAMILY, FailureEffect, COUNT(DISTINCT SERIAL_NUMBER) AS QTY
		FROM RC3_Data.[dbo].[RPT_TRIAGE_REPORT_VIEW_OUTPUT]
		WHERE MODEL_FAMILY IN ('K35','K-MINI PLUS','K-MINI BASIC', 'K-LATTE', 'K80', 'K90', 'K-CAFÉ', 'K-DUO', 'K-DUO PLUS', 'K-DUO ESSENTIALS') and FailureModeSubSystem='No Defect Trace'
		GROUP BY MODEL_FAMILY,FailureEffect
		)A, 
	(SELECT MODEL_FAMILY, COUNT(DISTINCT SERIAL_NUMBER) AS QTY
		FROM RC3_Data.[dbo].[RPT_TRIAGE_REPORT_VIEW_OUTPUT]
		WHERE MODEL_FAMILY IN ('K35','K-MINI PLUS','K-MINI BASIC', 'K-LATTE', 'K80', 'K90', 'K-CAFÉ', 'K-DUO', 'K-DUO PLUS', 'K-DUO ESSENTIALS')
		GROUP BY MODEL_FAMILY)B
WHERE A.MODEL_FAMILY=B.MODEL_FAMILY

/* Record the end time. */
SET @t2 = GETDATE();


/* See if data was written to the target tables. Write status to JOB_MONITORING table. */
IF EXISTS (SELECT * FROM RC3_Data..APP_TRUE_UP	 WHERE CAST(UPDATE_DATE AS DATE)=CAST(GETDATE() AS DATE)) 
	INSERT INTO JOB_MONITORING
	VALUES ('Appliance','K35_TRUE_UP', 'Green', @t1, @t2, ' ');
ELSE
	INSERT INTO JOB_MONITORING
	VALUES ('Appliance','K35_TRUE_UP', 'Red', @t1, @t2, 'An error was encountered.');

END
GO

